# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PUPPETEER_SKIP_DOWNLOAD: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Runs a set of commands using the runners shell
      - name: Build CLI
        run: |
          cd ./cli
          npm ci
          npm run build

      - name: Build Libraries
        run: |
          cd ./m3-odin
          npm ci
          npm run build:libs

  # Run all automated tests
  test:
    # Depends on successful run of Build
    needs: build

    runs-on: ubuntu-latest

    env:
      PUPPETEER_SKIP_DOWNLOAD: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Runs tests for m3-odin
      - name: install packges for m3-odin
        run: |
          cd ./m3-odin
          npm ci

      - name: run tests and publish results
        uses: artiomtr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./m3-odin/projects/infor-up/m3-odin
